name = "LogRoller"
uuid = "c41e01d8-14e5-11ea-185b-e7eabed7be4b"
keywords = ["log", "rotate", "roller", "logrotate"]
license = "MIT"
authors = ["Tanmay Mohapatra <tanmaykm@gmail.com>"]
version = "0.2.0"

[compat]
julia = "1"
CodecZlib = "0.6"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
